In [9]:
import pandas as pd
import numpy as np

In [31]:
combo_df = pd.read_csv('../data/combined_hits.csv')
pmids_by_type = combo_df.groupby('type')['pubmed_id'].apply(set)

In [42]:
size = 10
np.random.seed(20)
a = np.random.choice(list(pmids_by_type['aff_ms']), size=10)
b = np.random.choice(list(pmids_by_type['transcriptomics']), size=10)
c = np.random.choice(list(pmids_by_type['gwas']), size=10)
d = np.random.choice(list(pmids_by_type['crispr']), size=10)

In [43]:
# APMS
a

array([29599191, 19295130, 26472337, 27307491, 30097533, 27503909,
       24075985, 29045831, 28068325, 30209976])

https://pubmed.ncbi.nlm.nih.gov/?term=29599191%2C+19295130%2C+26472337%2C+27307491%2C+30097533%2C+27503909%2C+24075985%2C+29045831%2C+28068325%2C+30209976&sort=pubdate&format=abstract&size=200

In [44]:
# transcriptomics
b

array([24004674, 20818426, 20956553, 25267067, 25901080, 25464849,
       23867476, 23576566, 22801492, 26313692])

https://pubmed.ncbi.nlm.nih.gov/?term=24004674%2C+20818426%2C+20956553%2C+25267067%2C+25901080%2C+25464849%2C++++++++23867476%2C+23576566%2C+22801492%2C+26313692&sort=pubdate&size=200

In [45]:
# gwas
c

array([20421499, 25772935, 29210060, 31600170, 20154341, 24014518,
       21708048, 23571587, 25281659, 26822151])

https://pubmed.ncbi.nlm.nih.gov/?term=20421499%2C+25772935%2C+29210060%2C+31600170%2C+20154341%2C+24014518%2C++++++++21708048%2C+23571587%2C+25281659%2C+26822151&sort=pubdate&size=200

In [46]:
# crispr
d

array([31294695, 29526696, 28877469, 28877469, 30930145, 30194290,
       30647128, 31353312, 31294695, 28894007])

https://pubmed.ncbi.nlm.nih.gov/?term=31294695%2C+29526696%2C+28877469%2C+28877469%2C+30930145%2C+30194290%2C++++++++30647128%2C+31353312%2C+31294695%2C+28894007&sort=pubdate&size=200

In [40]:
combo_df[(combo_df['pubmed_id'] == 19295130)].sort_values('mentioned')

      gene_ncbi  pubmed_id  mentioned  mentioned_citations   hit    type
1943     8065.0   19295130      False                False  True  aff_ms
1973    80067.0   19295130      False                False  True  aff_ms
1974    64708.0   19295130      False                False  True  aff_ms
1975    64326.0   19295130      False                False  True  aff_ms
1976    57542.0   19295130      False                False  True  aff_ms
1977    55626.0   19295130      False                False  True  aff_ms
1978    84861.0   19295130      False                False  True  aff_ms
1979     9684.0   19295130      False                False  True  aff_ms
1980    59349.0   19295130      False                False  True  aff_ms
1981     8533.0   19295130      False                False  True  aff_ms
1982    80344.0   19295130      False                False  True  aff_ms
1983   115290.0   19295130      False                False  True  aff_ms
1984    53339.0   19295130      False                False  True  aff_ms
1985    54876.0   19295130      False                False  True  aff_ms
1986    55643.0   19295130      False                False  True  aff_ms
1987     6500.0   19295130      False                False  True  aff_ms
1988    10980.0   19295130      False                False  True  aff_ms
1989     9318.0   19295130      False                False  True  aff_ms
1990     1642.0   19295130      False                False  True  aff_ms
1991     1643.0   19295130      False                 True  True  aff_ms
1992    10987.0   19295130      False                 True  True  aff_ms
1993    23276.0   19295130      False                False  True  aff_ms
1994    55023.0   19295130      False                False  True  aff_ms
1995     8816.0   19295130      False                False  True  aff_ms
1996    51185.0   19295130      False                False  True  aff_ms
1997     9978.0   19295130      False                False  True  aff_ms
1972    51138.0   19295130      False                False  True  aff_ms
1998    25853.0   19295130      False                 True  True  aff_ms
1971    51514.0   19295130      False                False  True  aff_ms
1969    83892.0   19295130      False                False  True  aff_ms
1944     8450.0   19295130      False                 True  True  aff_ms
1945     8451.0   19295130      False                False  True  aff_ms
1946     8452.0   19295130      False                 True  True  aff_ms
1947     8453.0   19295130      False                False  True  aff_ms
1948     8454.0   19295130      False                 True  True  aff_ms
1949     9730.0   19295130      False                False  True  aff_ms
1950    10116.0   19295130      False                False  True  aff_ms
1951    11137.0   19295130      False                False  True  aff_ms
1952     6921.0   19295130      False                 True  True  aff_ms
1953     6923.0   19295130      False                False  True  aff_ms
1954   163590.0   19295130      False                False  True  aff_ms
1955     1161.0   19295130      False                False  True  aff_ms
1956    90379.0   19295130      False                 True  True  aff_ms
1957   122769.0   19295130      False                False  True  aff_ms
1958    55827.0   19295130      False                False  True  aff_ms
1959     7316.0   19295130      False                False  True  aff_ms
1960    55958.0   19295130      False                False  True  aff_ms
1961    55832.0   19295130      False                 True  True  aff_ms
1962    50717.0   19295130      False                False  True  aff_ms
1963     4738.0   19295130      False                False  True  aff_ms
1964    89890.0   19295130      False                False  True  aff_ms
1965    50813.0   19295130      False                False  True  aff_ms
1966    79269.0   19295130      False                False  True  aff_ms
1970    90293.0   19295130      False                False  True  aff_ms
1999    23038.0   19295130      False                False  True  aff_ms
1967    10920.0   19295130       True                 True  True  aff_ms
1968    79016.0   19295130       True                 True  True  aff_ms